name: Benchmark

on:
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: "${{ matrix.os.emoji }} ${{ matrix.python.name }}"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - emoji: 🐧
            runs-on: [ubuntu-latest]
          - emoji: 🍎
            runs-on: [macos-latest]
          - emoji: 🪟
            runs-on: [windows-latest]
        python:
          - name: CPython 3.13
            runs-on: "3.13"
          - name: CPython 3.12
            runs-on: "3.12"
          - name: CPython 3.11
            runs-on: "3.11"
          - name: CPython 3.10
            runs-on: "3.10"
          - name: CPython 3.9
            runs-on: "3.9"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          check-latest: true
          python-version: ${{ matrix.python.runs-on }}
      - run: python -m pip install -U pip wheel
      - run: python -m pip install -r requirements.txt
      - run: python -X utf8 bench-json.py
