name: Benchmark

on:
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: "${{ matrix.os.emoji }} ${{ matrix.python.name }}"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - emoji: 🐧
            runs-on: [ubuntu-latest]
          # - emoji: 🍎
          #   runs-on: [macos-latest]
          # - emoji: 🪟
          #   runs-on: [windows-latest]
        python:
          - name: CPython 3.7
            runs-on: "3.7"
          - name: CPython 3.8
            runs-on: "3.8"
          - name: CPython 3.9
            runs-on: "3.9"
          - name: CPython 3.10
            runs-on: "3.10"
          - name: CPython 3.11
            runs-on: "3.11"
          - name: CPython 3.12
            runs-on: "3.12-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.runs-on }}
      - run: python -m pip install -U pip wheel
      - name: Run
        run: ./bench-json.sh

